stages:
  prepare:
    cmd: python src/prepare.py --input_path /Users/ilyakaliya/Documents/11_kaliya_ml/uciHarClustering/data/raw/X_train.txt --output_path data/processed/df_scaled.csv
    deps:
      - src/prepare.py
      - /Users/ilyakaliya/Documents/11_kaliya_ml/uciHarClustering/data/raw/X_train.txt
      - /Users/ilyakaliya/Documents/11_kaliya_ml/uciHarClustering/data/raw/y_train.txt
    outs:
      - data/processed/df_scaled.csv
  reduce:
    cmd: python src/reduce.py --input_path data/processed/df_scaled.csv --output_path data/reduced/df_reduced.csv --params_path reduce_params.yaml
    deps:
      - src/reduce.py
      - data/processed/df_scaled.csv
      - reduce_params.yaml
    outs:
      - data/reduced/df_reduced.csv
  cluster:
    cmd: python src/cluster.py --input_path data/reduced/df_reduced.csv --output_path data/clustered/df_clustered.csv --params_path cluster_params.yaml --true_labels_path /Users/ilyakaliya/Documents/11_kaliya_ml/uciHarClustering/data/raw/y_train.txt
    deps:
      - src/cluster.py
      - data/reduced/df_reduced.csv
      - cluster_params.yaml
    outs:
      - data/clustered/df_clustered.csv
      - data/clustered/df_clustered_clusters_vs_labels.png
  evaluate:
    cmd: python src/evaluate.py --input_path data/reduced/df_reduced.csv --true_labels_path /Users/ilyakaliya/Documents/11_kaliya_ml/uciHarClustering/data/raw/y_train.txt --params_path evaluate_params.yaml --metrics_output_path metrics.json
    deps:
      - src/evaluate.py
      - data/reduced/df_reduced.csv
      - evaluate_params.yaml
      - /Users/ilyakaliya/Documents/11_kaliya_ml/uciHarClustering/data/raw/y_train.txt
    metrics:
      - metrics.json